//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public System.Guid UserDeviceID { get; set; }
        public string UserID { get; set; }
        public string DeviceID { get; set; }
        public string DeviceName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<short> RowVer { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
